### ISSUE TITLE
haxelib unavailable within sublime

### ISSUE THREAD

**Issue by Chuckytuh** [snowkit/sublime_flow#6]
I've installed haxe from homebrew, set up everything according to flow documentation within sublime but, every time I try to set "project.flow" as the current flow project, the following exception is thrown into sublime's console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "commands.flow_set_project_file in /Users/jppg/Library/Application Support/Sublime Text 3/Installed Packages/sublime_flow.sublime-package", line 11, in run
  File "flow in /Users/jppg/Library/Application Support/Sublime Text 3/Installed Packages/sublime_flow.sublime-package", line 62, in set_flow_file
  File "flow in /Users/jppg/Library/Application Support/Sublime Text 3/Installed Packages/sublime_flow.sublime-package", line 88, in refresh_info
  File "flow in /Users/jppg/Library/Application Support/Sublime Text 3/Installed Packages/sublime_flow.sublime-package", line 300, in run_process
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'haxelib'
```

haxe and haxelib is accessible from the OS terminal but not on sublime. The reason for this is that GUI applications do not have access to env variable set on .bashrc/.bash_profile files. 

There are two possible solutions that I found:
- Using [this fix](https://github.com/int3h/SublimeFixMacPath) or
- Setting an envvar for GUI apps as suggested [here](https://github.com/clemos/haxe-sublime-bundle/issues/117#issuecomment-38680014)

Sorry if this shouldn't be considered an issue here.

Cheers,
João.

**Comment by ruby0x1** [comment]
It's the right place for the issue, no worries.
And we were just debugging this today as it only presented with the new haxe installer location (fixed for El Capitan) and for some reason my install has no problems finding /usr/local/bin items - while @KeyMaster- had run into the same error.

This should be fixed soon, will report back when it is.
Thanks for the report and the immediate term fix via the plugin.
